apiVersion: v1
kind: ConfigMap
metadata:
  name: movie-config
  labels:
    app: movie-service
data:
  application.yml: |
    spring:
      datasource:
        url: jdbc:mysql://polar-mysql:3306/movie_db